## Basic Configuration

baseurl = "https://shenoybr.github.io/hugo-goa-demo/"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Erlich Bachman"
title = "Erlich Bachman"

theme = "hugo-goa"

## Hugo Built-in Features
disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "XYZ"
enableRobotsTXT = true

## Language settings
DefaultContentLanguage = "en"

[languages]
  [languages.en]
    contentDir = "content/"
    title = "My blog"
    weight = 10
  [languages.no]
    contentDir = "content/no"
    title = "Min Blog"
    weight = 20
    [languages.no.params]
      dateformat = "2 Jan, 2006"
      author = "Erlich Bachman"
      intro = "Grynder Guru Ekstraordinær"
      description = "No @Pied Piper. Tidligere @Hacker Hostel, @Bachmanity og @Aviato. <br/> \"Hva er F gange 5? Det er Fleventy-five.\""


## Site Settings
[params]
author = "Erlich Bachman"
intro = "Startup Guru Extraordinaire"
description = "Now @Pied Piper. Previously @Hacker Hostel, @Bachmanity and @Aviato. <br/> \"What is F times 5? It's Fleventy-five.\""
authorimage = "headshot.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Simple minimalist theme"
keywords = "minimalist,blog,goa,hugo,developer"

## Social Accounts
[params.social]
github = "<username>"
instagram = "<username>"
xing = "<username>"
linkedin = "<username>"
twitter = "<username>"
facebook = "<username>"
google = "<username>"
googlescholar = "<account_id>"
stackoverflow = "<username>"
lastfm = "<username>"
goodreads = "<username>"
gitlab = "<username>"
bitbucket = "<username>"
fivehundredpx = "<username>"
flickr = "<username>"
foursquare = "<username>"
hackernews = "<username>"
kickstarter = "<username>"
patreon = "<username>"
pintrest = "<username>"
steam = "<username>"
reddit = "<username>"
snapchat = "<username>"
youtube = "<channelid>"
keybase = "<username>"
twitch = "<username>"
soundcloud = "<username>"
tumblr = "<username>"
strava = "<username>"
skype = "<username>"
telegram = "<username>"
whatsapp = "<username>"
email = "you@example.com"
pgp = "<key_fingerprint>"

## Extras
[params.extra]
copyright = "© 2016. Erlich Bachman. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
poweredby = true
highlightjs = true
socialmarkup = true
toc = true
displayrssicon = true

## Main Menu
[[menu.main]]
    name = "blog"
    weight = 100
    identifier = "blog"
    url = "/blog/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"
[[menu.main]]
    name = "coderag"
    identifier = "coderag"
    weight = 300
    url = "/coderag/"

[[languages.no.menu.main]]
    name = "blogg"
    weight = 100
    identifier = "blog"
    url = "/blog/"
[[languages.no.menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"
[[languages.no.menu.main]]
    name = "coderag"
    identifier = "coderag"
    weight = 300
    url = "/coderag/"